# Copyright (C) 2025 RTE
# Copyright (C) 2026 Savoir-faire Linux, Inc.
# SPDX-License-Identifier: Apache-2.0

---
cephadm_release: "{{ ceph_version | default('20.2.0') }}"
cephadm_release_name: "tentacle"
cephadm_downloadbinary: false
cephadm_installbinary: false
cephadm_installrepo: false
cephadm_installcommon: false
cephadm_pullimages: false

# Registry configuration (for registry on ansible machine)
cephadm_registry_url: "{{ registry_url | default(null) }}"
cephadm_registry_auth_enabled: "{{ registry_auth_enabled | default(false) }}"
cephadm_registry_username: "{{ registry_username | default(null) }}"
cephadm_registry_password: "{{ registry_password | default(null) }}"
