# Copyright (C) 2025, RTE (http://www.rte-france.com)
# SPDX-License-Identifier: Apache-2.0

# This playbook configures and sets up Ceph with cephadm.

---

- name: Setup registry on ansible machine
  hosts: localhost
  gather_facts: true
  become: true
  vars:
    - ceph_registry_path: "../files/container_images/"
  roles:
    - role: ceph_registry
      when: registry_url is defined and registry_url is not none
